#!/usr/bin/env bash

# SCRIPT NAME: finder
# CREATION DATE: 2016-11-09
#
#
# DESCRIPTION: My Apple Finder preferential settings
#
# AUTHOR: Filipe Lemos <contato@filipelemos.com>
# AUTHOR URL: filipelemos.com

message_info "Finder settings"
defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true && killall Finder
defaults write com.apple.finder ShowPathbar -bool true && killall Finder
defaults write com.apple.finder ShowStatusBar -bool true &&  killall Finder
defaults write com.apple.finder WarnOnEmptyTrash -bool false && killall Finder
