#!/usr/bin/env bash

# SCRIPT NAME: time_machine
# CREATION DATE: 2016-11-09
#
#
# DESCRIPTION: My Apple Time Machine preferential settings
#
# AUTHOR: Filipe Lemos <contato@filipelemos.com>
# AUTHOR URL: filipelemos.com

message_info "Time Machine settings"
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true
hash tmutil &> /dev/null && sudo tmutil disablelocal
