#!/usr/bin/env bash

# SCRIPT NAME: transmission
# CREATION DATE: 2016-11-09
#
#
# DESCRIPTION: My Transmission BitTorrent client preferential settings
#
# AUTHOR: Filipe Lemos <contato@filipelemos.com>
# AUTHOR URL: filipelemos.com

message_info "Transmission settings"
defaults write org.m0k.transmission DeleteOriginalTorrent -bool true
defaults write org.m0k.transmission DownloadAsk -bool false
defaults write org.m0k.transmission DownloadFolder -string "${HOME}/Downloads/Torrents"
defaults write org.m0k.transmission IncompleteDownloadFolder -string "${HOME}/Downloads/Torrents/Incompletes"
defaults write org.m0k.transmission MagnetOpenAsk -bool false
defaults write org.m0k.transmission NSNavLastRootDirectory -string "${HOME}/Downloads/Torrents"
defaults write org.m0k.transmission UseIncompleteDownloadFolder -bool true
defaults write org.m0k.transmission WarningDonate -bool false
defaults write org.m0k.transmission WarningLegal -bool false
