#!/usr/bin/env bash

# SCRIPT NAME: brewcask
# CREATION DATE: 2016-10-28
#
#
# DESCRIPTION: My Brew Cask setup
#
# AUTHOR: Filipe Lemos <contato@filipelemos.com>
# AUTHOR URL: filipelemos.com

applications=(
  android-file-transfer
  appcleaner
  cmake
  diffmerge
  docker
  filezilla
  firefox
  flux
  font-menlo-for-powerline
  google-chrome
  itau
  iterm2
  java
  mactex
  macvim
  mongodb-compass
  opera
  osxfuse
  pomello
  slack
  selfcontrol
  skype
  spotify
  spotify-notifications
  teamviewer
  telegram
  tomighty
  transmission
  virtualbox
  virtualbox-extension-pack
  visual-studio-code
  vlc
)

echo "HOMEBREW SETUP"

echo "Configuring Brew Cask"
brew tap caskroom/cask
brew tap caskroom/fonts

echo "Installing Brew Cask applications"
brew cask install "${applications[@]}"
