#!/usr/bin/env bash

# SCRIPT NAME: brew
# CREATION DATE: 2016-10-28
#
#
# DESCRIPTION: My Brew setup
#
# AUTHOR: Filipe Lemos <contato@filipelemos.com>
# AUTHOR URL: filipelemos.com

applications=(
  ack
  bash
  coreutils
  doxygen
  ffmpeg
  findutils --with-default-names
  git
  git-lfs
  grep --with-default-names
  gzip
  hub
  libav
  mongodb
  node
  ntfs-3g
  openssh
  p7zip
  rsync
  speedtest_cli
  tmux
  tree
  unrar
  utf8proc
  wget
  youtube-dl
  zsh
)

echo "Configuring Brew"

echo "Installing Brew applications"
brew install "${applications[@]}"
