#!/usr/bin/env bash

# SCRIPT NAME: applications
# CREATION DATE: 2016-11-10
#
#
# DESCRIPTION: My macOS applications preferential settings
#
# AUTHOR: Filipe Lemos <contato@filipelemos.com>
# AUTHOR URL: filipelemos.com

message_info "macOS applications settings"

#######################################################################################################################
## APP STORE

# Check for software updates daily
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1

# Download the updates in background
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1

# Enabling automatic update check
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

# Install system data files and critical updates
defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1
#######################################################################################################################

#######################################################################################################################
## DOCK

# Auto-hiding dock
defaults write com.apple.dock autohide -bool true
defaults write com.apple.dock autohide-delay -float 0
defaults write com.apple.dock expose-animation-duration -float 0.10

# Dock icon size
defaults write com.apple.dock tilesize -int 32

# Enabling transparency
defaults write com.apple.dock hide-mirror -bool true

# Minimizing window effect
defaults write com.apple.dock mineffect -string "scale"

# Minimizing window into its application’s icon
defaults write com.apple.dock minimize-to-application -bool true

killall Dock
#######################################################################################################################

#######################################################################################################################
## FINDER

# Open a new Finder when a volume is mounted
defaults write com.apple.frameworks.diskimages auto-open-ro-root -bool true
defaults write com.apple.frameworks.diskimages auto-open-rw-root -bool true
defaults write com.apple.finder OpenWindowForNewRemovableDisk -bool true

# Displaying the path bar
defaults write com.apple.finder ShowPathbar -bool true

# Displaying the status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Empty Trash securely by default
defaults write com.apple.finder EmptyTrashSecurely -bool true

# No warning before cleaning the the trash
defaults write com.apple.finder WarnOnEmptyTrash -bool false

killall Finder
#######################################################################################################################

#######################################################################################################################
## ITERM2

# Allow clipboard access
defaults write com.googlecode.iterm2 AllowClipboardAccess -bool true

# Font settings
defaults write com.googlecode.iterm2 "Non Ascii Font" -string "MenloForPowerline-Regular 12"
defaults write com.googlecode.iterm2 "Normal Font" -string "Menlo-Regular 13"

# Install themes
open iTerm2/*.itermcolors

# Removing the dialog box when exiting the program
defaults write com.googlecode.iterm2 PromptOnQuit -bool false
#######################################################################################################################

#######################################################################################################################
## SAFARI

# Disabling standard delay in rendering a web page
defaults write com.apple.Safari WebKitInitialTimedLayoutDelay 0.25
#######################################################################################################################

#######################################################################################################################
## TEXTEDIT

# Opening and saving files in UTF-8 format
defaults write com.apple.TextEdit PlainTextEncoding -int 4
defaults write com.apple.TextEdit PlainTextEncodingForWrite -int 4

# Using plain text as the default text format in Apple's TextEdit
defaults write com.apple.TextEdit RichText -int 0
#######################################################################################################################

#######################################################################################################################
## TIME MACHINE

# Not show message to use external hard drives to backup
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true
hash tmutil &> /dev/null && sudo tmutil disablelocal
#######################################################################################################################

#######################################################################################################################
## TRANSMISSION

# Deleting the original torrent file
defaults write org.m0k.transmission DeleteOriginalTorrent -bool true

# Enabling incomplete download folder
defaults write org.m0k.transmission UseIncompleteDownloadFolder -bool true

# Folder settings
defaults write org.m0k.transmission DownloadFolder -string "${HOME}/Downloads/Torrents"
defaults write org.m0k.transmission IncompleteDownloadFolder -string "${HOME}/Downloads/Torrents/Incompletes"
defaults write org.m0k.transmission NSNavLastRootDirectory -string "${HOME}/Downloads/Torrents"

# Removing dialog boxes
defaults write org.m0k.transmission DownloadAsk -bool false
defaults write org.m0k.transmission MagnetOpenAsk -bool false
defaults write org.m0k.transmission WarningDonate -bool false
defaults write org.m0k.transmission WarningLegal -bool false
#######################################################################################################################
#!/usr/bin/env bash

# SCRIPT NAME: keyboard
# CREATION DATE: 2016-11-10
#
#
# DESCRIPTION: My macOS keyboard preferential settings
#
# AUTHOR: Filipe Lemos <contato@filipelemos.com>
# AUTHOR URL: filipelemos.com

message_info "Keyboard settings"

# Automatically illuminate the MacBook keyboard in low light
defaults write com.apple.BezelServices kDim -bool true

# Disabling press-and-hold for keys in favor of key repeat
defaults write NSGlobalDomain ApplePressAndHoldEnabled -bool true

# Enabling access for all controls (and Tab in modal dialogs)
defaults write NSGlobalDomain AppleKeyboardUIMode -int 3

# Faster react to keystrokes
defaults write NSGlobalDomain InitialKeyRepeat -int 12
defaults write NSGlobalDomain KeyRepeat -float 1

# Turn off keyboard illumination when computer is not used for 5 minutes
defaults write com.apple.BezelServices kDimTime -int 300

# Using scroll gesture with Ctrl (^) key to zoom
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
defaults write com.apple.universalaccess closeViewZoomFollowsFocus -bool true
defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144
#!/usr/bin/env bash

# SCRIPT NAME: macos
# CREATION DATE: 2016-11-09
#
#
# DESCRIPTION: My macOS preferential settings
#
# AUTHOR: Filipe Lemos <contato@filipelemos.com>
# AUTHOR URL: filipelemos.com

message_info "macOS settings"

COMPUTER_NAME=${USER}

# Avoid the creation of .DS_Store files in network volumes
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Allow NTFS volumes writing
sudo mv /sbin/mount_ntfs /sbin/mount_ntfs.original
sudo ln -s /usr/local/sbin/mount_ntfs /sbin/mount_ntfs

# Battery settings
defaults write com.apple.menuextra.battery ShowPercent -string "YES"

# Changing the computer name
sudo scutil --set ComputerName ${COMPUTER_NAME}

# Changing the screenshots folder
defaults write com.apple.screencapture location -string "${HOME}/Pictures/Screenshots"
defaults write com.apple.screencapture type -string "jpg"

# Date and time settings
sudo systemsetup -settimezone "America/Sao_Paulo" > /dev/null

# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Displaying system informations on login window
sudo defaults write /Library/Preferences/com.apple.loginwindow AdminHostInfo HostName

# Expanding save panel
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true

# Language and text format settings
defaults write NSGlobalDomain AppleLanguages -array "en-BR"
defaults write NSGlobalDomain AppleLocale -string "en_BR"
defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters"
defaults write NSGlobalDomain AppleMetricUnits -bool true

killall SystemUIServer
#!/usr/bin/env bash

# SCRIPT NAME: trackpad
# CREATION DATE: 2016-11-10
#
#
# DESCRIPTION: My trackpad preferential settings
#
# AUTHOR: Filipe Lemos <contato@filipelemos.com>
# AUTHOR URL: filipelemos.com

message_info "Trackpad settings"

# Enabling tap to click
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

# Mapping bottom right corner to right-click
defaults -currentHost write NSGlobalDomain com.apple.trackpad.enableSecondaryClick -bool true
defaults -currentHost write NSGlobalDomain com.apple.trackpad.trackpadCornerClickBehavior -int 1
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadCornerSecondaryClick -int 2
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadRightClick -bool true

# Swapping pages with three fingers
defaults -currentHost write NSGlobalDomain com.apple.trackpad.threeFingerHorizSwipeGesture -int 1
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad TrackpadThreeFingerVertSwipeGesture -int 2
defaults write NSGlobalDomain AppleEnableSwipeNavigateWithScrolls -bool true
