#!/usr/bin/env bash

echo "#################"
echo "### GIT SETUP ###"
echo "#################"
echo ""

if [[ ! -f $HOME/.gitconfig && ! -f $HOME/.gitignore_global ]]
then
  ln -sfnv "$HOME"/.dotfiles/git/.gitconfig "$HOME"/.gitconfig
  ln -sfnv "$HOME"/.dotfiles/git/.gitignore_global "$HOME"/.gitignore_global
else
  echo "Nothing to do here!"
fi
