#!/usr/bin/env bash

# shellcheck source=../helpers
. ../helpers

echo "GIT SETUP"

if [[ ! -f $HOME/.gitconfig && ! -f $HOME/.gitignore_global ]]
then
  symlink "$DOTFILES_PATH"/git/.gitconfig "$HOME"/.gitconfig
  symlink "$DOTFILES_PATH"/git/.gitignore_global "$HOME"/.gitignore_global
else
  echo "Nothing to do here!"
  exit
fi

echo "GIT SETUP IS COMPLETE!"
