#!/usr/bin/env bash

# shellcheck source=../helpers
. ../helpers

echo "GIT SETUP"

if [[ ! -f $HOME/.gitconfig && ! -f $HOME/.gitignore_global ]]
then
  symlink "$HOME"/.dotfiles/git/.gitconfig "$HOME"/.gitconfig
  symlink "$HOME"/.dotfiles/git/.gitignore_global "$HOME"/.gitignore_global
else
  echo "Nothing to do here!"
  exit
fi

echo "GIT SETUP IS COMPLETE!"
