#!/usr/bin/env bash

export DOTFILES_DIR="$PWD"/files

NORMAL_TEXT='\e[m'

GREEN='\e[32;1m'
PURPLE='\e[35;1m'
RED='\e[31;1m'
YELLOW='\e[33;1m'

create_link() {
	ln -sfnv "$1" "$2"
}

git_clone() {
  git clone --depth 1 https://github.com/"$1" "$2"
}

error_text() {
  echo ""
  echo -e "${RED}##### $* #####${NORMAL_TEXT}"
  sleep 2
}

header_text() {
  clear
  echo -e "${PURPLE}##### $* #####${NORMAL_TEXT}"
  sleep 2
}

success_text() {
  echo ""
  echo -e  "${GREEN}##### $* #####${NORMAL_TEXT}"
  sleep 2
}

warning_text() {
  echo ""
  echo -e "${YELLOW}##### $* #####${NORMAL_TEXT}"
  sleep 2
}
