#!/usr/bin/env bash

# SCRIPT NAME: setup.sh
# CREATION DATE: 2018-01-08
#
#
# DESCRIPTION: This script prepares my environment to work
#
# AUTHOR: Filipe Lemos <contato@filipelemos.com>
# AUTHOR URL: filipelemos.com

clear

echo "STARTING DOTFILES SETUP PROCESS"
sudo -v

# Update sudo while the script is running
while true; do sudo -n true; sleep 30; kill -0 "$$" || exit; done 2>/dev/null &

# case ${OSTYPE} in
#  darwin*)
#    . install/macos/brew_setup
#    . install/macos/macos_setup
#    ;;
#  *)
#    echo "Unknown operating system: $OSTYPE. Aborting" && exit 1
#    ;;
#esac

# . install/common/symlink_files
# . install/common/vim_setup
# . install/common/zsh_setup

#. $HOME/.zshrc

DOTFILES_DIR=$(pwd)
echo $DOTFILES_DIR
case $1 in
	-h | --help)
		echo "ajuda";;

	-f | --filipe)
		echo "filipe";;
	
	-t | --teste)
		. install_scripts/zsh_setup;;
	
	-l | --links)
		. install_scripts/symlink_files;;
esac

unset DOTFILES_DIR
echo "DOTFILES SETUP PROCESS FINISHED"
