#!/bin/bash

printOptions() {
    echo '1) Vim'
    echo '2) ZSH'
    echo
    echo '0) Encerrar'
    echo	
}

rest() {
    echo
    sleep 2
}

chooseOption() {
    printOptions

    read -p 'Escolha uma das opções acima: ' OPTION
    echo

    case $OPTION in
    0)
        exit
        ;;
    1)
        vimSetup
        chooseOption
        ;;
    2)
        zshSetup
        chooseOption
        ;;
    *)
        echo 'Opção inválida! Selecione uma das opções da lista.'
        rest
        chooseOption
        ;;
    esac
}

vimSetup(){
    echo 'SETUP DO VIM'
    rest

    if [ -f ~/.vimrc ]; then
        echo 'O arquivo .vimrc já está configurado nesse sistema.'
        rest
    else    
        echo 'Configurando o arquivo vimrc'
        ln -s ~/.dotfiles/vim/vimrc ~/.vimrc
        rest
    fi

    echo 'Verificando se o plugin vim-plug já está instalado.'
    rest
    if [ ! -d ~/.vim/autoload ]; then
        echo 'Instalando o plugin vim-plug para fazer o gerenciamento de plugins'
        curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    else
        echo 'O plugin vim-plug já está instalado e configurado nesse computador.'
        rest
    fi
}

zshSetup() {
    echo 'CONFIGURAÇÃO DO ZSH'
    rest

    if [ -f ~/.zshrc  ] && [ -L ~/.zshrc ]; then
        echo 'O arquivo .zshrc já está configurado nesse sistema.'
        rest
    elif [ -f ~/.zshrc ] && [ ! -L ~/.zshrc ]; then
        echo 'Removendo o .zshrc padrão e configurando o novo arquivo .zshrc'
        rm ~/.zshrc
        ln -s ~/.dotfiles/zsh/zshrc ~/.zshrc
        rest
    fi
}

while true;
do
    chooseOption
done
