#!/usr/bin/env bash

. packages

echo "#########################"
echo "### ARCH LINUX SETUP  ###"
echo "#########################"
echo ""

sudo pacman -Sy

echo "Installing AUR support by yay"
git clone https://aur.archlinux.org/yay-git.git
(
  cd yay-git || exit
  makepkg -si
  rm -rf yay-git
)

echo "Installing AUR packages"
yay -S "${AUR_PACKAGES[@]}"

echo "Installing Pacman packages"
yay -S "${PACMAN_PACKAGES[@]}" --noconfirm

echo "Cleaning temporary files"
yay -Sc
