#!/usr/bin/env bash

# shellcheck source=../helpers
. ../helpers

. packages

header_text "ARCH LINUX SETUP"

sudo pacman -Sy

warning_text "Installing AUR support by yay"
git clone https://aur.archlinux.org/yay-git.git
(
  cd yay-git || exit
  makepkg -si
  rm -rf yay-git
)

warning_text "Installing AUR packages"
yay -S "${AUR_PACKAGES[@]}"

warning_text "Installing Pacman packages"
yay -S "${PACMAN_PACKAGES[@]}" --noconfirm

warning_text "Cleaning temporary files"
yay -Sc

success_text "ARCH LINUX SETUP IS COMPLETE!"
