#!/usr/bin/env bash

export AUR_PACKAGES=(
  asdf-vm
  rar
  stockfish
  ttf-ms-fonts
  xp-pen-tablet
)

export PACMAN_PACKAGES=(
  chromium
  conky
  dbeaver
  discord
  firefox-developer-edition
  flatpak
  gimp
  gimp-help-en
  git-lfs
  github-cli
  gnuchess
  inkscape
  kde-applications
  krita
  meld
  neofetch
  obsidian
  p7zip
  python-pip
  reflector
  ruby
  shellcheck
  steam
  telegram-desktop
  tmux
  torbrowser-launcher
  ttf-fira-code
  ttf-roboto
  unzip
  virtualbox
  virtualbox-host-modules-arch
  youtube-dl
  zip
  zsh
)
