#!/usr/bin/env bash

echo "##################"
echo "### NANO SETUP ###"
echo "##################"
echo ""

if [[ ! -f $HOME/.nanorc ]]
then
  ln -sfnv "HOME"/.dotfiles/nano/.nanorc "$HOME"/.nanorc
else
  echo "Nothing to do here!"
fi
