#!/usr/bin/env bash

# shellcheck source=../helpers
. ../helpers

header_text "NANO SETUP"

if [[ ! -f $HOME/.nanorc ]]
then
  ln -sfnv "$DOTFILES_PATH"/nano/.nanorc "$HOME"/.nanorc
else
  echo "Nothing to do here!"
  exit
fi

success_text "NANO SETUP IS COMPLETE!"
