#!/usr/bin/env bash

# shellcheck source=../helpers
. ../helpers

echo "#################"
echo "### VIM SETUP ###"
echo "#################"
echo ""

if [[ ! -d $HOME/.vim ]]
then
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  symlink "$HOME"/.dotfiles/vim/.vimrc "$HOME"/.vimrc
else
  echo "Nothing to do here!"
fi
