#!/usr/bin/env bash

# shellcheck source=../helpers
. ../helpers

header_text "VIM SETUP"

if [[ ! -d $HOME/.vim ]]
then
  curl -fLo "$HOME"/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

  symlink "$HOME"/.dotfiles/vim/.vimrc "$HOME"/.vimrc
else
  warning_text "Nothing to do here!"
  exit
fi

success_text "VIM SETUP IS COMPLETE!"
