#!/usr/bin/env bash

# SCRIPT NAME: brew_setup
# CREATION DATE: 2016-10-25
#
#
# DESCRIPTION: This script automates my package installation with Homebrew.
#
# AUTHOR: Filipe Lemos

function brew_setup() {
  message_info "Configuring Homebrew"
  brew tap caskroom/cask
  brew tap caskroom/fonts
}

function brew_software_install() {
  message_info "Installing CLI tools"
  brew install bash htop-osx tree youtube-dl zsh zsh-completions

  message_info "Installing CLI development tools"
  brew install git hub utf8proc tmux
  brew install vim --with-override-system-vi

  message_info "Installing browsers"
  brew cask install firefox firefoxdeveloperedition google-chrome google-chrome-canary opera

  message_info "Installing fonts"
  brew cask install font-menlo-for-powerline

  message_info "Installing graphical software development tools"
  brew cask install diffmerge macvim sublime-text

  message_info "Installing graphical softwares"
  brew cask install android-file-transfer appcleaner iterm2 java pomello slack spotify spotify-notifications selfcontrol skype teamviewer tomighty utorrent vlc
}

message_info "HOMEBREW SETUP"
if [[ ! -f $(which brew) ]]; then
  message_info "Download and install Brew"
  ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  brew_setup
  brew_software_install
else
  message_info "Homebrew is already installed. Updating packages"
  brew update
  brew upgrade
  brew cleanup -n
fi
