#!/usr/bin/env bash

# SCRIPT NAME: brew_setup
# CREATION DATE: 2016-10-25
#
#
# DESCRIPTION: This script automates my package installation with Homebrew.
#
# AUTHOR: Filipe Lemos

message_info "HOMEBREW SETUP"

message_info "Installing CLI tools"
#brew install bash htop-osx tree youtube-dl zsh

message_info "Installing CLI development tools"
#brew install git hub tmux
#brew install vim --with-override-system-vi

message_info "Installing browsers"
#brew cask install firefox firefoxdeveloperedition google-chrome google-chrome-canary opera

message_info "Installing graphical tools"
#brew cask install diffmerge sublime-text

message_info "Installing graphical softwares"
#brew cask install android-file-transfer appcleaner iterm2 pomello slack spotify spotify-notifications selfcontrol skype teamviewer tomighty utorrent vlc

brew cleanup
