#!/usr/bin/env bash

# SCRIPT NAME: git_setup
# CREATION DATE: 2016-10-25
#
#
# DESCRIPTION: My Git setup
#
# AUTHOR: Filipe Lemos

. lib/messages
. lib/symlink_files

message_info "GIT SETUP"
symlink_file $HOME/.dotfiles/git/gitconfig $HOME/.gitconfig
symlink_file $HOME/.dotfiles/git/gitignore_global $HOME/.gitignore_global
