#!/usr/bin/env bash

function link_folder() {
  if [[ -d ${2} ]] && [[ -L ${2} ]]; then
    message_okay "The folder ${2} was already configured in this system"
  elif [[ ! -L ${2} ]]; then
    rm ${2}
    message_info "Configuring the folder ${2}"
    ln -s ${1} ${2}
  fi
}
