#!/usr/bin/env bash

# SCRIPT NAME: sublimetext_setup
# CREATION DATE: 2016-10-25
#
#
# DESCRIPTION: Setting up my Sublime Text settings
#
# AUTHOR: Filipe Lemos

message_info "SUBLIME TEXT 3 SETUP"

ST3_ORIGIN_FOLDER=$HOME/.dotfiles/sublime_text_3
ST3_DESTINATION_FOLDER=$HOME/Library/Application\ Support/Sublime\ Text\ 3/Packages/User

symlink_folder ${ST3_ORIGIN_FOLDER} ${ST3_DESTINATION_FOLDER}
