#!/usr/bin/env bash

function symlink_file() {
  if [[ -f ${2} ]] && [[ -L ${2} ]]; then
    message_okay "The file ${2} was already configured in this system"
  elif [[ ! -L ${2} ]]; then
    rm ${2}
    message_info "Configuring the file ${2}"
    ln -sfn ${1} ${2}
  fi
}
