#!/usr/bin/env bash

# shellcheck source=../helpers
. ../helpers

header_text "ASDF SETUP"

if [[ ! -d $HOME/.asdf ]]
then
  git clone https://github.com/asdf-vm/asdf.git "$HOME"/.asdf

  symlink "$HOME"/.dotfiles/asdf/.asdfrc "$HOME"/.asdfrc
  symlink "$HOME"/.dotfiles/asdf/.default-gems "$HOME"/.default-gems
  symlink "$HOME"/.dotfiles/asdf/.default-npm-packages "$HOME"/.default-npm-packages
  symlink "$HOME"/.dotfiles/asdf/.tool-versions "$HOME"/.tool-versions
else
  echo "Nothing to do here!"
  exit
fi

success_text "ASDF SETUP IS COMPLETE!"
