#!/usr/bin/env bash

# SCRIPT NAME: brewcask
# CREATION DATE: 2016-10-28
#
#
# DESCRIPTION: My Brew Cask setup
#
# AUTHOR: Filipe Lemos <contato@filipelemos.com>
# AUTHOR URL: filipelemos.com

applications=(
  android-file-transfer
  appcleaner
  cmake
  diffmerge
  docker
  firefox
  flux
  font-menlo-for-powerline
  google-chrome
  itau
  iterm2
  java
  macvim --override-system-vim --custom-system-icons
  opera
  osxfuse
  playonmac
  pomello
  slack
  selfcontrol
  skype
  spotify
  spotify-notifications
  sublime-text
  teamviewer
  tomighty
  transmission
  virtualbox
  virtualbox-extension-pack
  vlc
)

message_info "HOMEBREW SETUP"

message_info "Configuring Brew Cask"
brew tap caskroom/cask
brew tap caskroom/fonts

message_info "Installing Brew Cask applications"
brew cask install "${applications[@]}"
