#!/usr/bin/env bash

# SCRIPT NAME: brew
# CREATION DATE: 2016-10-28
#
#
# DESCRIPTION: My Brew setup
#
# AUTHOR: Filipe Lemos <contato@filipelemos.com>
# AUTHOR URL: filipelemos.com

applications=(
  bash
  coreutils
  ffmpeg
  findutils --with-default-names
  git-lfs
  grep --with-default-names
  gzip
  htop-osx
  hub
  libav
  openssh
  p7zip
  rsync
  speedtest_cli
  tmux
  tree
  unrar
  utf8proc
  vim --override-system-vi
  wget
  youtube-dl
  zsh
)

message_info "HOMEBREW SETUP"
brew tap homebrew/dupes

message_info "Installing Brew applications"
brew install "${applications[@]}"
