#!/usr/bin/env bash

# SCRIPT NAME: brew
# CREATION DATE: 2016-10-28
#
#
# DESCRIPTION: My Brew setup
#
# AUTHOR: Filipe Lemos <contato@filipelemos.com>
# AUTHOR URL: filipelemos.com

applications=(
  bash
  git
  git-lfs
  htop-osx
  hub
  openssh
  rsync
  speedtest_cli
  tmux
  tree
  unrar
  utf8proc
  vim --with-override-system-vi
  wget
  youtube-dl
  zsh
)

message_info "Downloading and installing Homebrew"
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

message_info "Configuring Brew"
brew tap homebrew/dupes

message_info "Installing applications"
brew install "${applications[@]}"
