#!/usr/bin/env bash

# SCRIPT NAME: brew
# CREATION DATE: 2016-10-28
#
#
# DESCRIPTION: My Brew setup
#
# AUTHOR: Filipe Lemos <contato@filipelemos.com>
# AUTHOR URL: filipelemos.com

applications=(
  bash
  coreutils
  findutils
  git-lfs
  grep
  htop-osx
  hub
  openssh
  p7zip
  rsync
  speedtest_cli
  tmux
  tree
  unrar
  utf8proc
  vim --with-override-system-vi
  wget
  youtube-dl
  zsh
)

message_info "Configuring Brew"
brew tap homebrew/dupes

message_info "Installing Brew applications"
brew install "${applications[@]}"
