#!/usr/bin/env bash

# SCRIPT NAME: git_setup
# CREATION DATE: 2016-10-25
#
#
# DESCRIPTION: Setting up my Git configuration files
#
# AUTHOR: Filipe Lemos <contato@filipelemos.com>
# AUTHOR URL: filipelemos.com

message_info "GIT SETUP"

symlink_file $HOME/.dotfiles/git/gitconfig $HOME/.gitconfig
symlink_file $HOME/.dotfiles/git/gitignore_global $HOME/.gitignore_global
