#!/usr/bin/env bash

# SCRIPT NAME: sublimetext_setup
# CREATION DATE: 2016-10-25
#
#
# DESCRIPTION: Setting up my Sublime Text settings
#
# AUTHOR: Filipe Lemos <contato@filipelemos.com>
# AUTHOR URL: filipelemos.com

message_info "SUBLIME TEXT 3 SETUP"
rm -rf ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User
ln -sFfnv ~/.dotfiles/sublime_text_3 ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User
