#!/usr/bin/env bash

# SCRIPT NAME: symlink_folders
# CREATION DATE: 2016-10-26
#
#
# DESCRIPTION: Custom functino to create symbolic links to folders
#
# AUTHOR: Filipe Lemos <contato@filipelemos.com>
# AUTHOR URL: filipelemos.com

function symlink_folder() {
  if [[ -d ${2} ]] && [[ -L ${2} ]]; then
    message_okay "The folder ${2} is already configured in this system"
  elif [[ ! -L ${2} ]]; then
    rm ${2}
    message_info "Configuring the folder ${2}"
    ln -sFfnv ${1} ${2}
  fi
}
