#!/usr/bin/env bash

# SCRIPT NAME: symlink_files
# CREATION DATE: 2016-10-25
#
#
# DESCRIPTION: Create symbolic links to files
#
# AUTHOR: Filipe Lemos <contato@filipelemos.com>
# AUTHOR URL: filipelemos.com

DOTFILES_PATH=~/.dotfiles/files

for file in $(ls ${DOTFILES_PATH}); do
  ln -sfnv ${DOTFILES_PATH}/${file} ~/.${file}
done

unset file
