#!/usr/bin/env bash

# SCRIPT NAME: vim_setup
# CREATION DATE: 2016-10-25
#
#
# DESCRIPTION: Setting up my GVim/Vim configuration
#
# AUTHOR: Filipe Lemos <contato@filipelemos.com>
# AUTHOR URL: filipelemos.com

message_info "VIM SETUP"
message_info "Vim-plug setup"
if [[ ! -d ~/.vim/autoload ]]; then
  message_info "Installing Vim-plug"
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
else
  message_okay "Vim-plug is already installed in this system"
fi

symlink_file ~/.dotfiles/vim/gvimrc ~/.gvimrc
symlink_file ~/.dotfiles/vim/vimrc ~/.vimrc
