#!/bin/bash

echo "Updating repositories and packages"
echo
sleep 2
brew update
brew upgrade

echo "Installing terminal applications"
echo
sleep 2
brew install htop-osx tmux

echo "Installing development tools"
echo
sleep 2
brew install hub

echo "Cleaning the cache"
echo
sleep2
brew cleanup
