#!/bin/bash

echo "Updating repositories and packages"
echo
sleep 2
brew cask update
brew cask upgrade

echo "Installing Caskroom"
echo
sleep 2
brew install caskroom/cask/brew-cask

echo "Installing applications"
echo
sleep 2
brew cask install android-file-transfer appcleaner filezilla iterm2 slack spotify spotify-notifications teamviewer utorrent virtualbox vlc

echo "Installing browsers"
echo
sleep 2
brew cask install google-chrome opera
brew cask install firefox-pt-br firefoxdeveloperedition

echo "Installing development tools"
echo
sleep 2
brew cask install atom diffmerge poedit

echo "Cleaning the cache"
echo
sleep 2
brew cask cleanup
