#!/bin/bash

echo "Installing Caskroom"
echo
sleep 2
brew install caskroom/cask/brew-cask

echo "Installing applications"
echo
sleep 2
brew cask install android-file-transfer appcleaner iterm2 teamviewer utorrent vlc

echo "Installing browsers"
echo
sleep 2
brew cask install firefox firefoxdeveloperedition google-chrome google-chrome-canary opera

echo "Installing development tools"
echo
sleep 2
brew cask install atom diffmerge dockertoolbox boot2docker

echo "Cleaning the cache"
echo
sleep 2
brew cask cleanup
