#!/bin/bash

echo
echo '#############################'
echo '#### CONFIGURAÇÃO DO GIT ####'
echo '#############################'
sleep 2
echo
    
if [ -f ~/.gitconfig ]; then
    echo 'O ARQUIVO .gitconfig JÁ ESTÁ CONFIGURADO NESSE SISTEMA.'
else
    echo 'CONFIGURANDO O ARQUIVO .gitconfig'
    ln -s ~/.dotfiles/git/gitconfig ~/.gitconfig
fi
