#!/usr/bin/env bash

brew install htop-osx

brew install git hub tmux

brew cleanup

brew cask install android-file-transfer appcleaner iterm2 slack spotify spotify-notifications teamviewer utorrent vlc

brew cask install firefox firefoxdeveloperedition google-chrome google-chrome-canary opera

brew cask install diffmerge
