#!/bin/bash

echo
echo '################'
echo '# SETUP DO VIM #'
echo '################'
sleep 2
echo

if [ -f ~/.vimrc ]; then
    echo 'O ARQUIVO .vimrc JÁ ESTÁ CONFIGURADO NESSE SISTEMA.'
else    
    echo 'CONFIGURANDO O ARQUIVO .vimrc'
    ln -s ~/.dotfiles/vimrc ~/.vimrc
fi

echo
echo 'VERIFICANDO SE O GERENCIADOR DE PLUGINS VIM-PLUG JÁ ESTÁ INSTALADO.'
sleep 2
echo

if [ ! -d ~/.vim/autoload ]; then
    echo 'INSTALANDO O PLUGIN VIM-PLUG'
    curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
else
    echo 'O PLUGIN VIM-PLUG JÁ ESTÁ INSTALADO E CONFIGURADO NESSE SISTEMA.'
fi
