#!/usr/bin/env bash

# shellcheck source=../helpers
. ../helpers

header_text "TMUX SETUP"

if [[ ! -d $HOME/.tmux/plugins/tpm ]]
then
  git clone https://github.com/tmux-plugins/tpm "$HOME"/.tmux/plugins/tpm

  symlink "$DOTFILES_PATH"/tmux/.tmux.conf "$HOME"/.tmux.conf
else
  warning_text "Nothing to do here!"
  exit
fi

success_text "TMUX SETUP IS COMPLETE!"
