#!/usr/bin/env bash

# shellcheck source=../helpers
. ../helpers

echo "#################"
echo "### ZSH SETUP ###"
echo "#################"
echo ""

if [[ ! -d $HOME/.oh-my-zsh ]]
then
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  sudo chsh -s "$(which zsh)" "$USER"
else
  echo "Nothing to do here!"
fi

symlink "$HOME"/.dotfiles/zsh/.zshenv "$HOME"/.zshenv
symlink "$HOME"/.dotfiles/zsh/.zshrc "$HOME"/.zshrc
