export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export editor="vim"

DEFAULT_USER="$USER"

CASE_SENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
DISABLE_UNTRACKED_FILES_DIRTY="true"
ENABLE_CORRECTION="true"

DISABLE_AUTO_UPDATE="false"
DISABLE_UPDATE_PROMPT="true"
UPDATE_ZSH_DAYS=3

ZSH_TMUX_AUTOSTART="true"
