. $HOME/.dotfiles/shell/aliases
. $HOME/.dotfiles/shell/exports
. $HOME/.dotfiles/shell/functions

CASE_SENSITIVE="true"
COMPLETION_WAITING_DOTS="true"
ENABLE_CORRECTION="true"
ZSH_THEME="avit"

plugins=(bower brew common-aliases git git-extras gitfast sublime tmux web-search)

# export MANPATH="/usr/local/man:$MANPATH"
. $ZSH/oh-my-zsh.sh
