alias grep='grep --color=auto'
alias history='history -i'
alias la='ls -la --color=auto'
alias ls='ls --color=auto'
alias nv='nvim'
alias ping='ping -c5'
alias pof='poweroff'
alias q='exit'
alias reb='reboot'
alias sc='shellcheck'
alias update='yay -Syu && yay -Sc --noconfirm'
