#!/usr/bin/env bash

# SCRIPT NAME: osx_setup
# CREATION DATE: 2016-10-26
#
#
# DESCRIPTION: Setting up OSX system and applications
#
# AUTHOR: Filipe Lemos

message_info "OSX CUSTOM CONFIGURATIONS"

message_okay "OSX CUSTOM CONFIGURATIONS FINISHED SUCCESSFULY"
