[tools]
go = "latest"
neovim = "latest"
node = "lts"
python = "system"
ruby = "latest"
shellcheck = "latest"
usage = "latest"

[settings]
always_keep_download = false
always_keep_install = false
asdf_compat = true
experimental = true
jobs = 5
legacy_version_file = true
plugin_autoupdate_last_check_duration = "1 week"
yes = true
